# Generated by Django 5.0.3 on 2024-04-05 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_comment_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="intrested_users",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
