# Generated by Django 5.0.3 on 2024-04-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_active_listing_intrested_users_listing_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.URLField(
                blank=True,
                default="https://powerusers.microsoft.com/t5/image/serverpage/image-id/98171iCC9A58CAF1C9B5B9/image-size/large/is-moderation-mode/true?v=v2&px=999",
            ),
        ),
    ]
