# Generated by Django 5.0.3 on 2024-08-06 23:03

from django.db import migrations

def update_category_values(apps, schema_editor):
    YourModel = apps.get_model('auctions', 'Listing')
    mapping = {
        'fruit': 'Food',
        'vehicle': 'Other',
        'furniture': 'Furniture',
        'pet':'pet',
        'tech':'Technology',
        '':'Other'
    }

    for old_value, new_value in mapping.items():
        YourModel.objects.filter(category=old_value).update(category=new_value)

class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_image'),
    ]

    # NOTE WHAT GOES HERE?
    operations = [
        migrations.RunPython(update_category_values),
    ]
