# Generated by Django 5.0.3 on 2024-08-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_highest_bid'),
    ]

    operations = [
    ]
