# Generated by Django 5.0.3 on 2024-08-07 14:34

from django.db import migrations
from django.db import migrations, models
from decimal import Decimal

def update_highest_bid(apps, schema_editor):
    Listing = apps.get_model('auctions', 'Listing')
    Bid = apps.get_model('auctions', 'Bid')

    for listing in Listing.objects.all():
        if listing.bids.exists():
            highest_bid = listing.bids.order_by('-amount').first().amount
        else:
            highest_bid = listing.starting_bid
        
        listing.highest_bid = highest_bid
        listing.save()

class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0008_update_highest_bid'),
    ]

    operations = [
        migrations.RunPython(update_highest_bid),
    ]
