# Generated by Django 5.0.3 on 2024-08-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_update_highest_bid2'),
    ]

    operations = [
    ]
